### ISSUE TITLE
Build failing on windows

### ISSUE THREAD

**Issue by justinmchase** [electron/libchromiumcontent#222]
Just following the build steps on the main README I am getting an error after running for a while. 

I'm on windows 10, x64. Running through git bash.

I'm not sure how to interpret this error message:

``` sh
justin@justin-pc MINGW64 /e/code/libchromiumcontent (master)
$ script/build -t x64
ninja: Entering directory `vendor\chromium\src\out\Release_x64'
[1/10903] LIB obj\third_party\angle\src\preprocessor.lib
[2/10903] ACTION Copying D3D Compiler DLL...
[3/10903] CXX obj\third_party\angle\src\compiler\translator\translator_lib.RegenerateStructNames.obj
[4/10903] CXX obj\third_party\angle\src\common\angle_common.debug.obj
[5/10903] CXX obj\third_party\angle\src\common\angle_common.tls.obj
[6/10903] CXX obj\third_party\angle\src\compiler\translator\translator_lib.BuiltInFunctionEmulator.obj
FAILED: C:\Python27\python.exe gyp-win-tool action-wrapper environment.x64 copy_compiler_dll_target_copy_dll_a30e198148542d4bce19a5c818c6884f..rsp ..\..\third_party\angle\src
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "script/build", line 52, in <module>
    sys.exit(main())
  File "script/build", line 38, in main
    subprocess.check_call([NINJA, '-C', config_dir, target])
  File "C:\Python27\lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['E:\\code\\libchromiumcontent\\vendor\\depot_tools\\ninja.exe', '-C', 'vendor\\chromium\\src\\out\\Release_x64', 'chromiumcontent_all']' returned non-zero exit status 1
```

**Comment by david-whitlark** [comment]
You need the https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk
installed

**Comment by justinmchase** [comment]
@david-whitlark I'll give it a try, thanks.

**Comment by justinmchase** [comment]
Perfect thanks.

**Comment by david-whitlark** [comment]
I also had to switch to Python 2.7.7 for the build to work as well

**Comment by lvdaqian** [comment]
It seems that you did not install the right windows SDK. I met that error in a 32bit windows.  And found that the path of windows SDK is wrong. In 32bit windows, it is not "Program Files (x86)", but "Program Files". You are in windows 10, it should not the same issue. But I think it is similar.   you can check the file "src\out\Release_x64\copy_compiler_dll_target_copy_dll_a30e198148542d4bce19a5c818c6884f..rsp" to find out the path the script looking for.
