### ISSUE TITLE
mac osx 10.11.16 build fail.

### ISSUE THREAD

**Issue by ikouchiha47** [electron/libchromiumcontent#244]
```
libchromiumcontent git:master ❯ script/build -t x64
ninja: Entering directory `src/out/Release'
[1200/11575] LINK mksnapshot, POSTBUILDS
ld: warning: direct access in v8::base::LazyInstanceImpl<v8::sampler::SamplerManager, v8::base::StaticallyAllocatedInstanceTrait<v8::sampler::SamplerManager>, v8::base::DefaultConstructTrait<v8::sampler::SamplerManager>, v8::base::ThreadSafeInitOnceTrait, v8::base::LeakyInstanceTrait<v8::sampler::SamplerManager> >::InitInstance(v8::base::StaticallyAllocatedInstanceTrait<v8::sampler::SamplerManager>::StorageType*) to global weak symbol v8::base::TemplateHashMapImpl<v8::base::DefaultAllocationPolicy>::PointersMatch(void*, void*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
[7862/11575] CXX obj/third_party/WebKit/Source/platform/blob/blink_platform.BlobData.o
FAILED: ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/third_party/WebKit/Source/platform/blob/blink_platform.BlobData.o.d -DU_COMBINED_IMPLEMENTATION -DUNISTR_FROM_CHAR_EXPLICIT= -DUNISTR_FROM_STRING_EXPLICIT= -DU_NO_DEFAULT_INCLUDE_UTF_HEADERS=0 -DV8_DEPRECATION_WARNINGS -D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORE=0 -DDISABLE_NACL -DCHROMIUM_BUILD -DCR_CLANG_REVISION=274142-1 -DUSE_LIBJPEG_TURBO=1 -DENABLE_WEBRTC=1 -DENABLE_MEDIA_ROUTER=1 -DUSE_PROPRIETARY_CODECS -DENABLE_PEPPER_CDMS -DENABLE_NOTIFICATIONS -DUSE_EXTERNAL_POPUP_MENU -DFIELDTRIAL_TESTING_ENABLED -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PDF=1 -DENABLE_PLUGIN_INSTALLATION=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DUSE_BROWSER_SPELLCHECKER=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_SERVICE_DISCOVERY=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DBLINK_PLATFORM_IMPLEMENTATION=1 -DINSIDE_BLINK -DENABLE_LAYOUT_UNIT_IN_INLINE_BOXES=0 -DENABLE_OILPAN=1 -DWTF_USE_CONCATENATED_IMPULSE_RESPONSES=1 -DWTF_USE_ICCJPEG=1 -DWTF_USE_QCMSLIB=1 -DSK_SUPPORT_GPU=1 -DSK_IGNORE_DW_GRAY_FIX -DSK_IGNORE_LINEONLY_AA_CONVEX_PATH_OPTS -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DU_NOEXCEPT= -DUSE_LIBPCI=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -D_FORTIFY_SOURCE=2 -Igen -I../../third_party/angle/include -Igen/blink -I../.. -I../../skia/config -I../../third_party/WebKit/Source -I../../third_party/khronos -I../../gpu -Igen/angle -I../../third_party/WebKit -Igen/third_party/WebKit -I../../third_party/boringssl/src/include -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/include/pdf -I../../third_party/skia/include/gpu -I../../third_party/skia/include/lazy -I../../third_party/skia/include/pathops -I../../third_party/skia/include/pipe -I../../third_party/skia/include/ports -I../../third_party/skia/include/utils -I../../third_party/skia/include/utils/mac -I../../skia/ext -I../../third_party/harfbuzz-ng/src -I../../third_party/iccjpeg -I../../third_party/icu/source/i18n -I../../third_party/icu/source/common -I../../third_party/libpng -I../../third_party/zlib -I../../third_party/libwebp -I../../third_party/ots/include -I../../third_party/qcms/src -I../../v8/include -I../../third_party/libjpeg_turbo -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -O2 -gdwarf-2 -fvisibility=hidden -Werror -mmacosx-version-min=10.8 -arch x86_64 -Wno-deprecated-declarations -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-selector-type-mismatch -Wpartial-availability -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -Wno-inconsistent-missing-override -Wno-shift-negative-value -Wno-undefined-var-template -Wno-nonportable-include-path -Wglobal-constructors -std=c++11 -stdlib=libc++ -fno-rtti -fno-exceptions -fvisibility-inlines-hidden -fno-threadsafe-statics -fcolor-diagnostics -Xclang -load -Xclang /Users/amitavaghosh/dev/js/libchromiumcontent/src/third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.dylib -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-templates -Xclang -plugin-arg-find-bad-constructs -Xclang follow-macro-expansion -Xclang -plugin-arg-find-bad-constructs -Xclang check-implicit-copy-ctors -fno-strict-aliasing -Xclang -load -Xclang /Users/amitavaghosh/dev/js/libchromiumcontent/src/third_party/llvm-build/Release+Asserts/lib/libBlinkGCPlugin.dylib -Xclang -add-plugin -Xclang blink-gc-plugin -include obj/third_party/WebKit/Source/build/mac/blink_platform.Prefix.h-cc -c ../../third_party/WebKit/Source/platform/blob/BlobData.cpp -o obj/third_party/WebKit/Source/platform/blob/blink_platform.BlobData.o
Invalid predicate in ICmp instruction!
  %cmp.i.i.i.i.i.i.i.i.i.i.i.i = icmp unknown %"struct.blink::BlobDataItem"* %lsr.iv.next3, null, !dbg !7912
fatal error: error in backend: Broken function found, compilation aborted!
clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 3.9.0 (trunk 274142)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Users/amitavaghosh/dev/js/libchromiumcontent/src/out/Release/../../third_party/llvm-build/Release+Asserts/bin
clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /var/folders/r8/px3gd_997vggvw57s80cbdqh0000gq/T/BlobData-ba7378.cpp
clang: note: diagnostic msg: /var/folders/r8/px3gd_997vggvw57s80cbdqh0000gq/T/BlobData-ba7378.sh
clang: note: diagnostic msg:

********************
[7862/11575] CXX obj/third_party/WebKit/Source/platform/exported/blink_platform.Platform.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "script/build", line 52, in <module>
    sys.exit(main())
  File "script/build", line 38, in main
    subprocess.check_call([NINJA, '-C', config_dir, target])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/haha/dev/js/libchromiumcontent/vendor/depot_tools/ninja', '-C', 'src/out/Release', 'chromiumcontent_all']' returned non-zero exit status 1
```

the cpp and sh files are here: https://gist.github.com/argentum47/8b1b0fff1db0ed6a9ead01c5f32cde28

**Comment by MarshallOfSound** [comment]
Hey there,

It's been a long time coming but the `libchromiumcontent` repository is being archived as it is no longer used in the Electron build system (🎉 this is a good thing).

If your issue is still relevant to Electron in it's current build system (please verify first) then you should probably raise a similar issue on `electron/electron`.

Thanks 😄
