### ISSUE TITLE
Build failure with Gnome SDK error: treating warnings as errors

### ISSUE THREAD

**Issue by mildred** [electron/libchromiumcontent#245]
Using GNOME flatpak SDK 3.20, I get the following error:

```
FAILED: if [ ! -e lib/libchromiumcontent.so -o ! -e lib/libchromiumcontent.so.TOC ]; then ../../third_party/llvm-build/Release+Asserts/bin/clang++ -shared -L/app/lib -Wl,-z,now -Wl,-z,relro -Wl,--fatal-warnings -Wl,-z,defs -pthread -Wl,-z,noexecstack -fPIC -fuse-ld=gold -B/run/build-runtime/electron-gtk3/electron/vendor/brightray/vendor/libchromiumcontent/vendor/chromium/src/third_party/binutils/Linux_x64/Release/bin -Wl,--disable-new-dtags -L. -Wl,-uIsHeapProfilerRunning,-uProfilerStart -Wl,-u_Z21InitialMallocHook_NewPKvj,-u_Z22InitialMallocHook_MMapPKvS0_jiiix,-u_Z22InitialMallocHook_SbrkPKvi -Wl,-u_Z21InitialMallocHook_NewPKvm,-u_Z22InitialMallocHook_MMapPKvS0_miiil,-u_Z22InitialMallocHook_SbrkPKvl -Wl,-u_ZN15HeapLeakChecker12IgnoreObjectEPKv,-u_ZN15HeapLeakChecker14UnIgnoreObjectEPKv -Wl,--export-dynamic -pthread -Wl,-uhb_ft_face_create_cached,-uhb_glib_get_unicode_funcs -m64 -Wl,--detect-odr-violations -Wl,--icf=all -Wl,-O1 -Wl,--as-needed -Wl,--gc-sections -o lib/libchromiumcontent.so -Wl,-soname=libchromiumcontent.so @lib/libchromiumcontent.so.rsp && { readelf -d lib/libchromiumcontent.so | grep SONAME ; nm -gD -f p lib/libchromiumcontent.so | cut -f1-2 -d' '; } > lib/libchromiumcontent.so.TOC; else ../../third_party/llvm-build/Release+Asserts/bin/clang++ -shared -L/app/lib -Wl,-z,now -Wl,-z,relro -Wl,--fatal-warnings -Wl,-z,defs -pthread -Wl,-z,noexecstack -fPIC -fuse-ld=gold -B/run/build-runtime/electron-gtk3/electron/vendor/brightray/vendor/libchromiumcontent/vendor/chromium/src/third_party/binutils/Linux_x64/Release/bin -Wl,--disable-new-dtags -L. -Wl,-uIsHeapProfilerRunning,-uProfilerStart -Wl,-u_Z21InitialMallocHook_NewPKvj,-u_Z22InitialMallocHook_MMapPKvS0_jiiix,-u_Z22InitialMallocHook_SbrkPKvi -Wl,-u_Z21InitialMallocHook_NewPKvm,-u_Z22InitialMallocHook_MMapPKvS0_miiil,-u_Z22InitialMallocHook_SbrkPKvl -Wl,-u_ZN15HeapLeakChecker12IgnoreObjectEPKv,-u_ZN15HeapLeakChecker14UnIgnoreObjectEPKv -Wl,--export-dynamic -pthread -Wl,-uhb_ft_face_create_cached,-uhb_glib_get_unicode_funcs -m64 -Wl,--detect-odr-violations -Wl,--icf=all -Wl,-O1 -Wl,--as-needed -Wl,--gc-sections -o lib/libchromiumcontent.so -Wl,-soname=libchromiumcontent.so @lib/libchromiumcontent.so.rsp && { readelf -d lib/libchromiumcontent.so | grep SONAME ; nm -gD -f p lib/libchromiumcontent.so | cut -f1-2 -d' '; } > lib/libchromiumcontent.so.tmp && if ! cmp -s lib/libchromiumcontent.so.tmp lib/libchromiumcontent.so.TOC; then mv lib/libchromiumcontent.so.tmp lib/libchromiumcontent.so.TOC ; fi; fi
/usr/lib/x86_64-unknown-linux/5.2.0/../../../x86_64-unknown-linux/bin/ld.gold: warning: hidden symbol 'sqlite3_busy_timeout' in libchromium_sqlite3.a(sqlite.sqlite3.o) is referenced by DSO /usr/lib/x86_64-unknown-linux/5.2.0/../../libsoftokn3.so
/usr/lib/x86_64-unknown-linux/5.2.0/../../../x86_64-unknown-linux/bin/ld.gold: warning: hidden symbol 'sqlite3_column_blob' in libchromium_sqlite3.a(sqlite.sqlite3.o) is referenced by DSO /usr/lib/x86_64-unknown-linux/5.2.0/../../libsoftokn3.so
/usr/lib/x86_64-unknown-linux/5.2.0/../../../x86_64-unknown-linux/bin/ld.gold: warning: hidden symbol 'sqlite3_reset' in libchromium_sqlite3.a(sqlite.sqlite3.o) is referenced by DSO /usr/lib/x86_64-unknown-linux/5.2.0/../../libsoftokn3.so
/usr/lib/x86_64-unknown-linux/5.2.0/../../../x86_64-unknown-linux/bin/ld.gold: warning: hidden symbol 'sqlite3_exec' in libchromium_sqlite3.a(sqlite.sqlite3.o) is referenced by DSO /usr/lib/x86_64-unknown-linux/5.2.0/../../libsoftokn3.so
/usr/lib/x86_64-unknown-linux/5.2.0/../../../x86_64-unknown-linux/bin/ld.gold: warning: hidden symbol 'sqlite3_open' in libchromium_sqlite3.a(sqlite.sqlite3.o) is referenced by DSO /usr/lib/x86_64-unknown-linux/5.2.0/../../libsoftokn3.so
/usr/lib/x86_64-unknown-linux/5.2.0/../../../x86_64-unknown-linux/bin/ld.gold: warning: hidden symbol 'sqlite3_bind_int' in libchromium_sqlite3.a(sqlite.sqlite3.o) is referenced by DSO /usr/lib/x86_64-unknown-linux/5.2.0/../../libsoftokn3.so
/usr/lib/x86_64-unknown-linux/5.2.0/../../../x86_64-unknown-linux/bin/ld.gold: warning: hidden symbol 'sqlite3_column_int' in libchromium_sqlite3.a(sqlite.sqlite3.o) is referenced by DSO /usr/lib/x86_64-unknown-linux/5.2.0/../../libsoftokn3.so
/usr/lib/x86_64-unknown-linux/5.2.0/../../../x86_64-unknown-linux/bin/ld.gold: warning: hidden symbol 'sqlite3_step' in libchromium_sqlite3.a(sqlite.sqlite3.o) is referenced by DSO /usr/lib/x86_64-unknown-linux/5.2.0/../../libsoftokn3.so
/usr/lib/x86_64-unknown-linux/5.2.0/../../../x86_64-unknown-linux/bin/ld.gold: warning: hidden symbol 'sqlite3_close' in libchromium_sqlite3.a(sqlite.sqlite3.o) is referenced by DSO /usr/lib/x86_64-unknown-linux/5.2.0/../../libsoftokn3.so
/usr/lib/x86_64-unknown-linux/5.2.0/../../../x86_64-unknown-linux/bin/ld.gold: warning: hidden symbol 'sqlite3_column_bytes' in libchromium_sqlite3.a(sqlite.sqlite3.o) is referenced by DSO /usr/lib/x86_64-unknown-linux/5.2.0/../../libsoftokn3.so
/usr/lib/x86_64-unknown-linux/5.2.0/../../../x86_64-unknown-linux/bin/ld.gold: warning: hidden symbol 'sqlite3_temp_directory' in libchromium_sqlite3.a(sqlite.sqlite3.o) is referenced by DSO /usr/lib/x86_64-unknown-linux/5.2.0/../../libsoftokn3.so
/usr/lib/x86_64-unknown-linux/5.2.0/../../../x86_64-unknown-linux/bin/ld.gold: warning: hidden symbol 'sqlite3_bind_text' in libchromium_sqlite3.a(sqlite.sqlite3.o) is referenced by DSO /usr/lib/x86_64-unknown-linux/5.2.0/../../libsoftokn3.so
/usr/lib/x86_64-unknown-linux/5.2.0/../../../x86_64-unknown-linux/bin/ld.gold: warning: hidden symbol 'sqlite3_bind_blob' in libchromium_sqlite3.a(sqlite.sqlite3.o) is referenced by DSO /usr/lib/x86_64-unknown-linux/5.2.0/../../libsoftokn3.so
/usr/lib/x86_64-unknown-linux/5.2.0/../../../x86_64-unknown-linux/bin/ld.gold: warning: hidden symbol 'sqlite3_finalize' in libchromium_sqlite3.a(sqlite.sqlite3.o) is referenced by DSO /usr/lib/x86_64-unknown-linux/5.2.0/../../libsoftokn3.so
/usr/lib/x86_64-unknown-linux/5.2.0/../../../x86_64-unknown-linux/bin/ld.gold: warning: hidden symbol 'sqlite3_prepare_v2' in libchromium_sqlite3.a(sqlite.sqlite3.o) is referenced by DSO /usr/lib/x86_64-unknown-linux/5.2.0/../../libsoftokn3.so
/usr/lib/x86_64-unknown-linux/5.2.0/../../../x86_64-unknown-linux/bin/ld.gold: warning: hidden symbol 'sqlite3_file_control' in libchromium_sqlite3.a(sqlite.sqlite3.o) is referenced by DSO /usr/lib/x86_64-unknown-linux/5.2.0/../../libsoftokn3.so
/usr/lib/x86_64-unknown-linux/5.2.0/../../../x86_64-unknown-linux/bin/ld.gold: warning: hidden symbol 'sqlite3_free' in libchromium_sqlite3.a(sqlite.sqlite3.o) is referenced by DSO /usr/lib/x86_64-unknown-linux/5.2.0/../../libsoftokn3.so
/usr/lib/x86_64-unknown-linux/5.2.0/../../../x86_64-unknown-linux/bin/ld.gold: warning: hidden symbol 'sqlite3_mprintf' in libchromium_sqlite3.a(sqlite.sqlite3.o) is referenced by DSO /usr/lib/x86_64-unknown-linux/5.2.0/../../libsoftokn3.so
/usr/lib/x86_64-unknown-linux/5.2.0/../../../x86_64-unknown-linux/bin/ld.gold: error: treating warnings as errors
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "script/build", line 52, in <module>
    sys.exit(main())
  File "script/build", line 38, in main
    subprocess.check_call([NINJA, '-C', config_dir, target])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/run/build-runtime/electron-gtk3/electron/vendor/brightray/vendor/libchromiumcontent/vendor/depot_tools/ninja', '-C', 'vendor/chromium/src/out/Release', 'chromiumcontent_all']' returned non-zero exit status 1
```

Perhaps libchromiumcontent should't build chromium with linker flag `-Wl,--fatal-warnings`

The issue is that `libsoftokn3.so` (nss library) references symbols from sqlite. nss isn'tl linked statically with nss, but dynamically. libchromiumcontent uses a static link (symbols are embedded and marked hidden).

I don't see the problem with that. nss will resolve its references to sqlite at runtime using the libsqlite.so library, and libchromiumcontent will use the static library it embeds. Why would the linker complain ?

The linker complains because it thinks that the nss library will want to resolve sqlite symbols in libchromiumcontent, but it should resolve those symbols with an external libsqlite instead.

**Comment by MarshallOfSound** [comment]
Hey there,

It's been a long time coming but the `libchromiumcontent` repository is being archived as it is no longer used in the Electron build system (🎉 this is a good thing).

If your issue is still relevant to Electron in it's current build system (please verify first) then you should probably raise a similar issue on `electron/electron`.

Thanks 😄
