### ISSUE TITLE
Please help on how to apply this patch and build

### ISSUE THREAD

**Issue by demian85** [electron/libchromiumcontent#252]
Hi guys, 

I need to apply [this patch](https://codereview.chromium.org/2617143003) to chromium, build libchromiumcontent and then Electron to test if bug has been fixed, but I'm really lost.
I've just read [this](https://medium.com/juan-cruz-viotti/how-to-submit-a-chromium-patch-to-libchromiumcontent-d8886d1b289b#.rdcak17q3) article explaining how, but still no clue on how to glue libchromiumcontent with chromium... If I apply patch in chromium, how to proceed then?
How does libchromiumcontent know where to locate chromium? Where should I clone it?

Then, if this works, is there any chance you could apply that patch too? My project depends on this feature to work.

Thanks.

**Comment by kevinsawicki** [comment]
> I've just read this article explaining how, but still no clue on how to glue libchromiumcontent with chromium

That article looks correct but you probably don't need to actually clone chromium.

You may be able to just clone this repository, copy https://codereview.chromium.org/download/issue2617143003_1_10001.diff to the `patches/` folder, commit it, and then follow the other build instructions in that article.

The build part will take awhile since the builds can take hours since it compiles ~15,000 files.

**Comment by kevinsawicki** [comment]
> Then, if this works, is there any chance you could apply that patch too?

Usually we don't apply unreleased patches unless they are security related or critical bug fixes.

Also, that patch was just committed last week so their may be additional follow on fixes or other issues that come up once that patch gets released in a canary build.

**Comment by demian85** [comment]
Well, patch couldn't be applied somehow so I made changes manually. Then...

```
MacRamboPro:libchromiumcontent demian$ ./script/build
ninja: Entering directory `src/out/Release'
ninja: fatal: chdir to 'src/out/Release' - No such file or directory
Traceback (most recent call last):
  File "./script/build", line 52, in <module>
    sys.exit(main())
  File "./script/build", line 38, in main
    subprocess.check_call([NINJA, '-C', config_dir, target])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/demian/www/libchromiumcontent/vendor/depot_tools/ninja', '-C', 'src/out/Release', 'chromiumcontent_all']' returned non-zero exit status 1```

What's going on?

**Comment by kevinsawicki** [comment]
> What's going on?

Did you run `script/bootstrap` before that?

**Comment by demian85** [comment]
Sure, just like README says...
```
script/bootstrap
script/update -t x64
script/build -t x64
```

Should I run it again after patching?

**Comment by kevinsawicki** [comment]
> Should I run it again after patching?

No, just running `script/build -t x64` to build should be enough.

What is in your `src/out` folder?

**Comment by demian85** [comment]
Ok. Ran `update` script again and now it's compiling 👍

**Comment by demian85** [comment]
Well, no luck at all...
```
MacRamboPro:libchromiumcontent demian$ ./script/build
ninja: Entering directory `src/out/Release'
[2570/13833] LINK mksnapshot, POSTBUILDS
ld: warning: direct access in function 'v8::base::LazyInstanceImpl<v8::sampler::SamplerManager, v8::base::StaticallyAllocatedInstanceTrait<v8::sampler::SamplerManager>, v8::base::DefaultConstructTrait<v8::sampler::SamplerManager>, v8::base::ThreadSafeInitOnceTrait, v8::base::LeakyInstanceTrait<v8::sampler::SamplerManager> >::InitInstance(v8::base::StaticallyAllocatedInstanceTrait<v8::sampler::SamplerManager>::StorageType*)' from file 'libv8_libsampler.a(v8_libsampler.v8-sampler.o)' to global weak symbol 'v8::base::TemplateHashMapImpl<v8::base::DefaultAllocationPolicy>::PointersMatch(void*, void*)' from file 'libv8_base.a(v8_base.spaces.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
[7148/13833] CXX obj/printing/backend/printing.print_backend_cups.o
FAILED: ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/printing/backend/printing.print_backend_cups.o.d -DU_COMBINED_IMPLEMENTATION -DUNISTR_FROM_CHAR_EXPLICIT= -DUNISTR_FROM_STRING_EXPLICIT= -DU_NO_DEFAULT_INCLUDE_UTF_HEADERS=0 -DV8_DEPRECATION_WARNINGS -D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORE=0 -DDISABLE_NACL -DCHROMIUM_BUILD -DCR_CLANG_REVISION=274142-1 -DUSE_LIBJPEG_TURBO=1 -DENABLE_WEBRTC=1 -DENABLE_MEDIA_ROUTER=1 -DUSE_PROPRIETARY_CODECS -DENABLE_PEPPER_CDMS -DENABLE_NOTIFICATIONS -DUSE_EXTERNAL_POPUP_MENU -DFIELDTRIAL_TESTING_ENABLED -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PDF=1 -DENABLE_PLUGIN_INSTALLATION=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DUSE_BROWSER_SPELLCHECKER=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_SERVICE_DISCOVERY=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DPRINTING_IMPLEMENTATION -DPRINT_BACKEND_AVAILABLE -DSK_SUPPORT_GPU=1 -DSK_IGNORE_DW_GRAY_FIX -DSK_IGNORE_LINEONLY_AA_CONVEX_PATH_OPTS -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DU_NOEXCEPT= -DUSE_CUPS -DUSE_LIBPCI=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -D_FORTIFY_SOURCE=2 -Igen -I../.. -I../../skia/config -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/include/pdf -I../../third_party/skia/include/gpu -I../../third_party/skia/include/lazy -I../../third_party/skia/include/pathops -I../../third_party/skia/include/pipe -I../../third_party/skia/include/ports -I../../third_party/skia/include/utils -I../../third_party/skia/include/utils/mac -I../../skia/ext -I../../third_party/icu/source/i18n -I../../third_party/icu/source/common -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -O2 -gdwarf-2 -fvisibility=hidden -Werror -mmacosx-version-min=10.8 -arch x86_64 -Wno-deprecated-declarations -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-selector-type-mismatch -Wpartial-availability -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -Wno-inconsistent-missing-override -Wno-shift-negative-value -Wno-undefined-var-template -Wno-nonportable-include-path -std=c++11 -stdlib=libc++ -fno-rtti -fno-exceptions -fvisibility-inlines-hidden -fno-threadsafe-statics -fcolor-diagnostics -Xclang -load -Xclang /Users/demian/www/libchromiumcontent/src/third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.dylib -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-templates -Xclang -plugin-arg-find-bad-constructs -Xclang follow-macro-expansion -Xclang -plugin-arg-find-bad-constructs -Xclang check-implicit-copy-ctors -fno-strict-aliasing  -c ../../printing/backend/print_backend_cups.cc -o obj/printing/backend/printing.print_backend_cups.o
../../printing/backend/print_backend_cups.cc:243:21: error: use of undeclared identifier 'cupsGetPPD'
    ppd_file_path = cupsGetPPD(name);
                    ^
../../printing/backend/print_backend_cups.cc:256:21: error: use of undeclared identifier 'cupsGetPPD2'
    ppd_file_path = cupsGetPPD2(http.http(), name);
                    ^
2 errors generated.
[7148/13833] CXX obj/services/shell/public/cpp/lib/shell_public.capabilities.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "./script/build", line 52, in <module>
    sys.exit(main())
  File "./script/build", line 38, in main
    subprocess.check_call([NINJA, '-C', config_dir, target])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/demian/www/libchromiumcontent/vendor/depot_tools/ninja', '-C', 'src/out/Release', 'chromiumcontent_all']' returned non-zero exit status 1```

**Comment by kevinsawicki** [comment]
> ppd_file_path = cupsGetPPD(name);

This error is https://github.com/electron/libchromiumcontent/issues/241, see that issue for workarounds.

**Comment by demian85** [comment]
Right, so after applying my patch and a whole day of compilation, this is what I get when building Electron with chrome54 branch.
```
MacRamboPro:electron demian$ ./script/build.py -c D
ninja: Entering directory `out/D'
[905/1405] CXX obj/vendor/crashpad/util/net/crashpad_util.http_body.o
FAILED: ../../vendor/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/vendor/crashpad/util/net/crashpad_util.http_body.o.d -DENABLE_WEBRTC -DNDEBUG -DV8_USE_EXTERNAL_STARTUP_DATA -DSK_SUPPORT_LEGACY_GETTOPDEVICE -DSK_SUPPORT_LEGACY_BITMAP_CONFIG -DSK_SUPPORT_LEGACY_DEVICE_VIRTUAL_ISOPAQUE -DSK_SUPPORT_LEGACY_N32_NAME -DSK_SUPPORT_LEGACY_SETCONFIG -DSK_IGNORE_ETC1_SUPPORT -DSK_IGNORE_GPU_DITHER -DDISABLE_NACL -DUSE_OPENSSL -DWEBRTC_MAC -DDEBUG -DCOMPONENT_BUILD -DGURL_DLL -DSKIA_DLL -DUSING_V8_SHARED -DWEBKIT_DLL -I../../vendor/crashpad -Iobj/vendor/crashpad/util/crashpad_util.gen -I/Users/demian/www/electron/vendor/brightray/vendor/download/libchromiumcontent/src -I../../vendor/crashpad/compat/mac -I../../vendor/crashpad/compat/non_cxx11_lib -I../../vendor/crashpad/compat/non_win -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -fasm-blocks -mpascal-strings -O0 -gdwarf-2 -Werror -mmacosx-version-min=10.9 -arch x86_64 -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-deprecated-declarations -Wno-undefined-var-template -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -Wno-unused-private-field -std=c++11 -stdlib=libc++ -fno-rtti -fno-exceptions -fcolor-diagnostics  -c ../../vendor/crashpad/util/net/http_body.cc -o obj/vendor/crashpad/util/net/crashpad_util.http_body.o
../../vendor/crashpad/util/net/http_body.cc:92:3: error: use of undeclared identifier 'STLDeleteContainerPointers'; did you mean 'base::STLDeleteContainerPointers'?
  STLDeleteContainerPointers(parts_.begin(), parts_.end());
  ^~~~~~~~~~~~~~~~~~~~~~~~~~
  base::STLDeleteContainerPointers
/Users/demian/www/electron/vendor/brightray/vendor/download/libchromiumcontent/src/base/stl_util.h:42:6: note: 'base::STLDeleteContainerPointers' declared here
void STLDeleteContainerPointers(ForwardIterator begin, ForwardIterator end) {
     ^
1 error generated.
[905/1405] OBJCXX obj/vendor/crashpad/util/net/crashpad_util.http_transport_mac.o
ninja: build stopped: subcommand failed.```

**Comment by demian85** [comment]
Sorry, I suppose I had to checkout chrome54 branch on Elexctron repo too, but this is my output...
```
MacRamboPro:electron demian$ git checkout chrome54
Branch chrome54 set up to track remote branch chrome54 from origin.
Switched to a new branch 'chrome54'
MacRamboPro:electron demian$ ./script/bootstrap.py -v --url file:///Users/demian/www/libchromiumcontent
Running in verbose mode
git submodule sync --recursive
git submodule update --init --recursive
Submodule 'vendor/boto' (https://github.com/boto/boto.git) registered for path 'vendor/boto'
Submodule 'vendor/breakpad' (https://github.com/electron/chromium-breakpad.git) registered for path 'vendor/breakpad'
Submodule 'vendor/brightray' (https://github.com/electron/brightray.git) registered for path 'vendor/brightray'
Submodule 'vendor/crashpad' (https://github.com/electron/crashpad.git) registered for path 'vendor/crashpad'
Submodule 'vendor/depot_tools' (https://chromium.googlesource.com/chromium/tools/depot_tools.git) registered for path 'vendor/depot_tools'
Submodule 'vendor/native_mate' (https://github.com/zcbenz/native-mate.git) registered for path 'vendor/native_mate'
Submodule 'vendor/node' (https://github.com/electron/node.git) registered for path 'vendor/node'
Submodule 'vendor/requests' (https://github.com/kennethreitz/requests) registered for path 'vendor/requests'
Cloning into '/Users/demian/www/electron/vendor/boto'...
Cloning into '/Users/demian/www/electron/vendor/breakpad'...
Cloning into '/Users/demian/www/electron/vendor/brightray'...
Cloning into '/Users/demian/www/electron/vendor/crashpad'...
Cloning into '/Users/demian/www/electron/vendor/depot_tools'...
Cloning into '/Users/demian/www/electron/vendor/native_mate'...
Cloning into '/Users/demian/www/electron/vendor/node'...
Cloning into '/Users/demian/www/electron/vendor/requests'...
Submodule path 'vendor/boto': checked out 'f7574aa6cc2c819430c1f05e9a1a1a666ef8169b'
Submodule path 'vendor/breakpad': checked out 'c566c50d81f7b1edeaee9f11f5d07bda858d6b64'
Submodule 'src' (https://chromium.googlesource.com/breakpad/breakpad/src) registered for path 'vendor/breakpad/src'
Cloning into '/Users/demian/www/electron/vendor/breakpad/src'...
Submodule path 'vendor/breakpad/src': checked out '33a43757f6dadf49cb2240d22f1d0d827bfeae8f'
Submodule path 'vendor/brightray': checked out 'f99b71c172d3871d515d9c992b547eec1139875a'
Submodule 'vendor/google-styleguide' (https://github.com/svn2github/sgss-mirror-google-styleguide) registered for path 'vendor/brightray/vendor/google-styleguide'
Submodule 'vendor/gyp' (https://github.com/electron/gyp) registered for path 'vendor/brightray/vendor/gyp'
Submodule 'vendor/libchromiumcontent' (https://github.com/electron/libchromiumcontent) registered for path 'vendor/brightray/vendor/libchromiumcontent'
Cloning into '/Users/demian/www/electron/vendor/brightray/vendor/google-styleguide'...
Cloning into '/Users/demian/www/electron/vendor/brightray/vendor/gyp'...
Cloning into '/Users/demian/www/electron/vendor/brightray/vendor/libchromiumcontent'...
Submodule path 'vendor/brightray/vendor/google-styleguide': checked out 'ba88c8a53f1b563c43fc063cc048e5efdc238c18'
Submodule path 'vendor/brightray/vendor/gyp': checked out '549e55a22765ccf99e46b419b2dff6338bcac64a'
error: no such remote ref e4f8c1821e6180d4f05e3597f4da031bf808f470
Fetched in submodule path 'vendor/brightray/vendor/libchromiumcontent', but it did not contain e4f8c1821e6180d4f05e3597f4da031bf808f470. Direct fetching of that commit failed.
Submodule path 'vendor/crashpad': checked out 'c58712f998445983dfea73da6478194b6c52c3cb'
Submodule path 'vendor/depot_tools': checked out '4fa73b8ca6899bc69577932b80145a6bf07e4424'
Submodule path 'vendor/native_mate': checked out 'b5e5de626c6a57e44c7e6448d8bbaaac475d493c'
Submodule path 'vendor/node': checked out '811cfe3fcd360179d3dd436e3d80e1b045adf633'
Submodule path 'vendor/requests': checked out 'e4d59bedfd3c7f4f254f4f5d036587bcd8152458'
Failed to recurse into submodule path 'vendor/brightray'
None
Traceback (most recent call last):
  File "./script/bootstrap.py", line 264, in <module>
    sys.exit(main())
  File "./script/bootstrap.py", line 34, in main
    update_submodules()
  File "./script/bootstrap.py", line 128, in update_submodules
    execute_stdout(['git', 'submodule', 'update', '--init', '--recursive'])
  File "/Users/demian/www/electron/script/lib/util.py", line 180, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['git', 'submodule', 'update', '--init', '--recursive']' returned non-zero exit status 1
```

Please help

**Comment by kevinsawicki** [comment]
@demian85 looks like you got it building now? https://bugs.chromium.org/p/chromium/issues/detail?id=678269#c34

Can this be closed?

**Comment by kevinsawicki** [comment]
Closing out and continuing the discussion in #253
