### ISSUE TITLE
Build process failing, please help

### ISSUE THREAD

**Issue by demian85** [electron/libchromiumcontent#269]
As posted on [Discuss](https://discuss.atom.io/t/please-help-with-custom-build-process-weird-ninja-error/40367). I'm trying to build libchromiumcontent based on chromium 58.
All patches applied correctly, but when executing `script/build -t x64` I'm getting the following error:
```
./script/build -t x64
ninja: Entering directory `src/out/Release'
ninja: error: '../../net/data/ssl/wosign/wosign_domains.gperf', needed by 'gen/net/data/ssl/wosign/wosign_domains-inc.cc', missing and no known rule to make it
Traceback (most recent call last):
  File "./script/build", line 56, in <module>
    sys.exit(main())
  File "./script/build", line 42, in main
    subprocess.check_call([NINJA, '-C', config_dir, target], env=env)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/demian/www/libchromiumcontent/vendor/depot_tools/ninja', '-C', 'src/out/Release', 'chromiumcontent:chromiumcontent']' returned non-zero exit status 1
```
Using Mac OSX 10.12.3.
I'll be happy to submit pull request if this works. It took me almost 2 days to fix patches.

Thanks.

**Comment by demian85** [comment]
?

**Comment by kuoruan** [comment]
Enter the dir ```net/data/ssl/wosign/```, you should see a file ```wosign_domains.gperf```

https://chromium.googlesource.com/chromium/src/+/master/net/data/ssl/wosign/

**Comment by demian85** [comment]
It's not there, the only file in that folder is BUILD.gn. How's that?

**Comment by kuoruan** [comment]
I am not sure, maybe you can try ```git checkout net/data/ssl/wosign/```

**Comment by demian85** [comment]
Just copied missing files there (not sure if the right revision), but it's
compiling now (trying with Chrome 58 again since 100% sure that's what I
need).
Will keep you posted!
Thanks!

**Comment by demian85** [comment]
Well, new failure... :(
How come many files are missing? Just did as specified in readme: ./script/bootstrap, ./script/update and ./script/build.

Chrome 58:
```
./script/build
ninja: Entering directory `src/out/Release'
[833/19197] ACTION //content/common:mojo_bindings_shared__generator(//build/toolchain/mac:clang_x64)
FAILED: gen/content/common/render_message_filter.mojom-shared-internal.h gen/content/common/render_message_filter.mojom-shared.cc gen/content/common/render_message_filter.mojom-shared.h
python ../../mojo/public/tools/bindings/mojom_bindings_generator.py --use_bundled_pylibs generate ../../content/common/render_message_filter.mojom -d ../../ -I ../../ -o /Users/demian/www/libchromiumcontent/src/out/Release/gen --bytecode_path /Users/demian/www/libchromiumcontent/src/out/Release/gen/mojo/public/tools/bindings -I ../../mojo/services --generate_non_variant_code -g c++
../../content/common/mojo/common/common_custom_types.mojom: Error: No such file or directory
  ../../content/common/mojo/common/common_custom_types.mojom was imported by ../../content/common/render_message_filter.mojom
[838/19197] ACTION //content/common:mojo_bindings_shared__generator(//build/toolchain/mac:clang_x64)
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "./script/build", line 56, in <module>
    sys.exit(main())
  File "./script/build", line 42, in main
    subprocess.check_call([NINJA, '-C', config_dir, target], env=env)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/demian/www/libchromiumcontent/vendor/depot_tools/ninja', '-C', 'src/out/Release', 'chromiumcontent:chromiumcontent']' returned non-zero exit status 1
```

Chrome 57:
```
./script/build
ninja: Entering directory `src/out/Release'
[714/18689] ACTION //content/common:mojo_bindings_shared__generator(//build/toolchain/mac:clang_x64)
FAILED: gen/content/common/render_message_filter.mojom-shared-internal.h gen/content/common/render_message_filter.mojom-shared.cc gen/content/common/render_message_filter.mojom-shared.h
python ../../mojo/public/tools/bindings/mojom_bindings_generator.py --use_bundled_pylibs generate ../../content/common/render_message_filter.mojom -d ../../ -I ../../ -o /Users/demian/www/libchromiumcontent-original/src/out/Release/gen --bytecode_path /Users/demian/www/libchromiumcontent-original/src/out/Release/gen/mojo/public/tools/bindings -I ../../mojo/services --generate_non_variant_code -g c++
../../content/common/mojo/common/common_custom_types.mojom: Error: No such file or directory
  ../../content/common/mojo/common/common_custom_types.mojom was imported by ../../content/common/render_message_filter.mojom
[719/18689] ACTION //content/common:mojo_bindings_shared__generator(//build/toolchain/mac:clang_x64)
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "./script/build", line 56, in <module>
    sys.exit(main())
  File "./script/build", line 42, in main
    subprocess.check_call([NINJA, '-C', config_dir, target], env=env)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/demian/www/libchromiumcontent-original/vendor/depot_tools/ninja', '-C', 'src/out/Release', 'chromiumcontent:chromiumcontent']' returned non-zero exit status 1
```

**Comment by kuoruan** [comment]
Follow the official doc step by step, can download the entire source.

https://chromium.googlesource.com/chromium/src/+/master/docs/mac_build_instructions.md#Prerequisites

**Comment by demian85** [comment]
Sure, but I don't understand why do I need to build chromium myself if libchromiumcontent will do that automatically for me. Am I wrong?
Btw, I found out a few files in source code changed, I need to check patches.

**Comment by demian85** [comment]
Well, this worked, but now electron build fails and I'm stuck again :(

```
./script/build.py
ninja: Entering directory `out/R'
[498/1131] CXX obj/vendor/crashpad/util/file/crashpad_util.string_file.o
FAILED: ../../vendor/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/vendor/crashpad/util/file/crashpad_util.string_file.o.d -DENABLE_WEBRTC -DNDEBUG -DV8_USE_EXTERNAL_STARTUP_DATA -DSK_SUPPORT_LEGACY_GETTOPDEVICE -DSK_SUPPORT_LEGACY_BITMAP_CONFIG -DSK_SUPPORT_LEGACY_DEVICE_VIRTUAL_ISOPAQUE -DSK_SUPPORT_LEGACY_N32_NAME -DSK_SUPPORT_LEGACY_SETCONFIG -DSK_IGNORE_ETC1_SUPPORT -DSK_IGNORE_GPU_DITHER -DDISABLE_NACL -DUSE_OPENSSL -DWEBRTC_MAC -I../../vendor/crashpad -Iobj/vendor/crashpad/util/crashpad_util.gen -I/Users/demian/www/electron/vendor/brightray/vendor/download/libchromiumcontent/src -I../../vendor/crashpad/compat/mac -I../../vendor/crashpad/compat/non_cxx11_lib -I../../vendor/crashpad/compat/non_win -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -fasm-blocks -mpascal-strings -O2 -gdwarf-2 -Werror -mmacosx-version-min=10.9 -arch x86_64 -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-deprecated-declarations -Wno-undefined-var-template -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -Wno-unused-private-field -Wno-address-of-packed-member -std=c++11 -stdlib=libc++ -fno-rtti -fno-exceptions -fcolor-diagnostics -fno-inline -fno-omit-frame-pointer -fno-builtin -fno-optimize-sibling-calls  -c ../../vendor/crashpad/util/file/string_file.cc -o obj/vendor/crashpad/util/file/crashpad_util.string_file.o
../../vendor/crashpad/util/file/string_file.cc:170:10: error: no viable conversion from returned value of type 'StrictNumeric<unsigned long>' to function return type 'FileOffset' (aka 'long long')
  return offset_.ValueOrDie();
         ^~~~~~~~~~~~~~~~~~~~
/Users/demian/www/electron/vendor/brightray/vendor/download/libchromiumcontent/src/base/numerics/safe_conversions.h:218:17: note: candidate template ignored: disabled by 'enable_if' [with Dst = long long]
                IsNumericRangeContained<Dst, T>::value>::type* = nullptr>
                ^
1 error generated.
```

**Comment by cifratila** [comment]
@demian85 You need to follow these steps in order to upgrade to latest version of Chromium and be able to build electron using it: [Upgrading Chromium](https://github.com/electron/electron/blob/master/docs/development/upgrading-chrome.md)

**Comment by kevinsawicki** [comment]
Closing this out now that Chrome 58 has been upgraded to.
