### ISSUE TITLE
Error building libchromiumcontent on Mac OS X version 10.12.6

### ISSUE THREAD

**Issue by anupam** [electron/libchromiumcontent#366]
I am trying to modify some build switches to the libchromium content, getting this error on building it on Mac OS X. 
```
`ninja: Entering directory `src/out-x64/static_library
[7953/18664] OBJCXX obj/device/bluetooth/bluetooth/bluetooth_adapter_mac.o
FAILED: obj/device/bluetooth/bluetooth/bluetooth_adapter_mac.o
../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/device/bluetooth/bluetooth/bluetooth_adapter_mac.o.d -DDEVICE_BLUETOOTH_IMPLEMENTATION -DV8_DEPRECATION_WARNINGS -DNO_TCMALLOC -DDISABLE_NACL -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DENABLE_MEDIA_ROUTER=1 -DFIELDTRIAL_TESTING_ENABLED -DCR_CLANG_REVISION=\"299960-1\" -DCR_XCODE_VERSION=0900 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORE=0 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DENABLE_IPC_FUZZER -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DHAVE_PTHREAD -DSK_IGNORE_LINEONLY_AA_CONVEX_PATH_OPTS -DSK_SUPPORT_GPU=1 -DSK_BUILD_FOR_MAC -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -I../.. -Igen -I../../third_party/boringssl/src/include -I../../third_party/protobuf/src -Igen/protoc_out -I../../third_party/protobuf/src -I../../skia/config -I../../skia/ext -I../../third_party/skia/include/c -I../../third_party/skia/include/config -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/include/images -I../../third_party/skia/include/lazy -I../../third_party/skia/include/pathops -I../../third_party/skia/include/pdf -I../../third_party/skia/include/pipe -I../../third_party/skia/include/ports -I../../third_party/skia/include/utils -I../../third_party/skia/include/gpu -I../../third_party/skia/src/gpu -I../../third_party/skia/src/sksl -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -fno-strict-aliasing -fstack-protector -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -fcolor-diagnostics -arch x86_64 -Wall -Werror -Wextra -Wpartial-availability -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -Wno-undefined-var-template -Wno-nonportable-include-path -Wno-address-of-packed-member -Wno-unused-lambda-capture -Wno-user-defined-warnings -O2 -fno-omit-frame-pointer -gdwarf-2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.9 -fvisibility=hidden -Xclang -load -Xclang ../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.dylib -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-auto-raw-pointer -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -fvisibility-inlines-hidden -std=c++11 -stdlib=libc++ -fobjc-call-cxx-cdtors -Wobjc-missing-property-synthesis -fno-rtti -fno-exceptions -c ../../device/bluetooth/bluetooth_adapter_mac.mm -o obj/device/bluetooth/bluetooth/bluetooth_adapter_mac.o
../../device/bluetooth/bluetooth_adapter_mac.mm:157:69: error: comparison of two values with different enumeration types ('CBManagerState' and 'CBCentralManagerState') [-Werror,-Wenum-compare]
    is_present = is_present || ([low_energy_central_manager_ state] !=
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
../../device/bluetooth/bluetooth_adapter_mac.mm:166:69: error: comparison of two values with different enumeration types ('CBManagerState' and 'CBCentralManagerState') [-Werror,-Wenum-compare]
    is_powered = is_powered || ([low_energy_central_manager_ state] ==
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
2 errors generated.
[7962/18664] ACTION //third_party/libvpx:libvpx_yasm_action(//build/toolchain/mac:clang_x64)
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "script/build", line 66, in <module>
    sys.exit(main())
  File "script/build", line 45, in main
    subprocess.check_call([NINJA, '-C', os.path.relpath(out_dir), target], env=env)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/ashah/playground/electron/vendor/libchromiumcontent/vendor/depot_tools/ninja', '-C', 'src/out-x64/static_library', 'chromiumcontent:chromiumcontent']' returned non-zero exit status 1``
```

**Comment by cifratila** [comment]
@anupam Libchromiumcontent, as Chromium, needs SDK 10.10 in order to compile.

How to install older SDK: https://github.com/devernay/xcodelegacy
