### ISSUE TITLE
x64 build fails on windows

### ISSUE THREAD

**Issue by anupam** [electron/libchromiumcontent#373]
Seeing this error when trying to build for x64 on Windows 10, with Visual Studio 2015 update 3 

```
ninja: Entering directory `src\out-x64\static_library'                                                                                                                                                                                       [11191/18516] CXX obj/media/media/decoder_selector.obj
FAILED: obj/media/media/decoder_selector.obj
C:/Python27/python.exe ../../build/toolchain/win/tool_wrapper.py cl-wrapper ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64/cl.exe" /nologo /showIncludes /FC @obj/media/media/decoder_selector.obj.rsp /c ../../media/filters/decoder_selector.cc /Foobj/media/media/decoder_selector.obj obj/media "media_cc.pdb"
c:\users\denimuser\playground\libchromiumcontent\src\media\filters\decoder_selector.cc(246): error C2220: warning treated as error - no 'object' file generated
c:\users\denimuser\playground\libchromiumcontent\src\media\filters\decoder_selector.cc(246): warning C4661: 'void media::DecoderSelector<media::DemuxerStream::VIDEO>::InitializeDecryptingDecoder(void)': no suitable definition provided for explicit template instantiation request
c:\users\denimuser\playground\libchromiumcontent\src\media\filters\decoder_selector.h(83): note: see declaration of 'media::DecoderSelector<media::DemuxerStream::VIDEO>::InitializeDecryptingDecoder'
c:\users\denimuser\playground\libchromiumcontent\src\media\filters\decoder_selector.cc(246): warning C4661: 'void media::DecoderSelector<media::DemuxerStream::VIDEO>::DecryptingDecoderInitDone(bool)': no suitable definition provided for explicit template instantiation request
c:\users\denimuser\playground\libchromiumcontent\src\media\filters\decoder_selector.h(84): note: see declaration of 'media::DecoderSelector<media::DemuxerStream::VIDEO>::DecryptingDecoderInitDone'
c:\users\denimuser\playground\libchromiumcontent\src\media\filters\decoder_selector.cc(245): warning C4661: 'void media::DecoderSelector<media::DemuxerStream::AUDIO>::InitializeDecryptingDecoder(void)': no suitable definition provided for explicit template instantiation request
c:\users\denimuser\playground\libchromiumcontent\src\media\filters\decoder_selector.h(83): note: see declaration of 'media::DecoderSelector<media::DemuxerStream::AUDIO>::InitializeDecryptingDecoder'
c:\users\denimuser\playground\libchromiumcontent\src\media\filters\decoder_selector.cc(245): warning C4661: 'void media::DecoderSelector<media::DemuxerStream::AUDIO>::DecryptingDecoderInitDone(bool)': no suitable definition provided for explicit template instantiation request
c:\users\denimuser\playground\libchromiumcontent\src\media\filters\decoder_selector.h(84): note: see declaration of 'media::DecoderSelector<media::DemuxerStream::AUDIO>::DecryptingDecoderInitDone'
c:\users\denimuser\playground\libchromiumcontent\src\media\filters\decoder_selector.cc(52): warning C4661: 'void media::DecoderSelector<media::DemuxerStream::VIDEO>::InitializeDecryptingDecoder(void)': no suitable definition provided for explicit template instantiation request
c:\users\denimuser\playground\libchromiumcontent\src\media\filters\decoder_selector.h(83): note: see declaration of 'media::DecoderSelector<media::DemuxerStream::VIDEO>::InitializeDecryptingDecoder'
c:\users\denimuser\playground\libchromiumcontent\src\media\filters\decoder_selector.cc(52): warning C4661: 'void media::DecoderSelector<media::DemuxerStream::VIDEO>::DecryptingDecoderInitDone(bool)': no suitable definition provided for explicit template instantiation request
c:\users\denimuser\playground\libchromiumcontent\src\media\filters\decoder_selector.h(84): note: see declaration of 'media::DecoderSelector<media::DemuxerStream::VIDEO>::DecryptingDecoderInitDone'
c:\users\denimuser\playground\libchromiumcontent\src\media\filters\decoder_selector.cc(52): warning C4661: 'void media::DecoderSelector<media::DemuxerStream::AUDIO>::InitializeDecryptingDecoder(void)': no suitable definition provided for explicit template instantiation request
c:\users\denimuser\playground\libchromiumcontent\src\media\filters\decoder_selector.h(83): note: see declaration of 'media::DecoderSelector<media::DemuxerStream::AUDIO>::InitializeDecryptingDecoder'
c:\users\denimuser\playground\libchromiumcontent\src\media\filters\decoder_selector.cc(52): warning C4661: 'void media::DecoderSelector<media::DemuxerStream::AUDIO>::DecryptingDecoderInitDone(bool)': no suitable definition provided for explicit template instantiation request
c:\users\denimuser\playground\libchromiumcontent\src\media\filters\decoder_selector.h(84): note: see declaration of 'media::DecoderSelector<media::DemuxerStream::AUDIO>::DecryptingDecoderInitDone'
[11200/18516] CXX obj/content/public/browser/browser_sources/web_contents_observer.obj
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "script\build", line 66, in <module>
    sys.exit(main())
  File "script\build", line 45, in main
    subprocess.check_call([NINJA, '-C', os.path.relpath(out_dir), target], env=env)
  File "C:\Python27\lib\subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\denimuser\\playground\\libchromiumcontent\\vendor\\depot_tools\\ninja.exe', '-C', 'src\\out-x64\\static_library', 'chromiumcontent:chromiumcontent']' returned non-zero exit status 1
```

**Comment by anupam** [comment]
Is any one able to compile 64 bit ?

**Comment by anupam** [comment]
From the slack channel, for electron I got to know that this can be the issue with Windows SDK version, the read me link for this repo is pointing to build the latest chromium in the prerequisite, which asks to install Visual Studio 2017, I think the version of Chromium requires Visual Studio 2015 update 3 and I have Windows SDK 10.0.14393.795. Can any body point me to the correct version of Visual Studio and Windows SDK to install?

**Comment by alexeykuzmin** [comment]
@anupam 

> to build the latest chromium in the prerequisite

I don't have to build Chromium to build libcc.

> Can any body point me to the correct version of Visual Studio and Windows SDK to install?

The latest libcc is based on Chromium 59.0.3071.115, here are its build instructions for Windows: https://chromium.googlesource.com/chromium/src/+/59.0.3071.115/docs/windows_build_instructions.md You can find system requirements and environment setup instructions there.

Closed.

**Comment by anupam** [comment]
Thanks it helped and I was able to build it.
