### ISSUE TITLE
`script/build -t x64  --no_static_library` fails

### ISSUE THREAD

**Issue by tejainece** [electron/libchromiumcontent#412]
Running `script/build -t x64  --no_static_library` fails with following error:

```
ninja: Entering directory `src/out-x64/shared_library'
[655/17945] ACTION //third_party/WebKit/Source/platform:color_data(//build/toolchain/linux:clang_x64)
FAILED: gen/blink/platform/ColorData.cpp 
python ../../third_party/WebKit/Source/build/scripts/gperf.py gperf --key-positions=\* -D -s 2 ../../third_party/WebKit/Source/platform/ColorData.gperf --output-file=gen/blink/platform/ColorData.cpp
Traceback (most recent call last):
  File "../../third_party/WebKit/Source/build/scripts/gperf.py", line 26, in <module>
    main()
  File "../../third_party/WebKit/Source/build/scripts/gperf.py", line 23, in main
    subprocess.check_call(unknownargs)
  File "/usr/lib/python2.7/subprocess.py", line 536, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[660/17945] ACTION //components/resources:about_credits(//build/toolchain/linux:clang_x64)
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "./script/build", line 87, in <module>
    sys.exit(main())
  File "./script/build", line 64, in main
    subprocess.check_call([NINJA, '-C', os.path.relpath(out_dir), target], env=env)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['libchromiumcontent/vendor/depot_tools/ninja', '-C', 'src/out-x64/shared_library', 'chromiumcontent:chromiumcontent']' returned non-zero exit status 1
```

**Comment by MarshallOfSound** [comment]
Hey there,

It's been a long time coming but the `libchromiumcontent` repository is being archived as it is no longer used in the Electron build system (🎉 this is a good thing).

If your issue is still relevant to Electron in it's current build system (please verify first) then you should probably raise a similar issue on `electron/electron`.

Thanks 😄
