### ISSUE TITLE
Error Creating Distribution on OS X

### ISSUE THREAD

**Issue by joshelson** [electron/libchromiumcontent#547]
Have this reproducible error on attempting to create a distribution. Everything up to this point works perfectly, but `create-dist` fails with this error sequence:

```
$ ./script/create-dist -t x64
ninja: Entering directory `/Users/josh/dev/joshelson/libchromiumcontent/dist/main'
[18288/18288] LICENSE
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: can't open file: /Users/josh/dev/joshelson/libchromiumcontent/dist/main/native_mksnapshot/libffmpeg.dylib (No such file or directory)
Traceback (most recent call last):
  File "./script/create-dist", line 765, in <module>
    sys.exit(main())
  File "./script/create-dist", line 392, in main
    args.target_arch)
  File "./script/create-dist", line 561, in strip_binaries
    create_debug_archive)
  File "./script/create-dist", line 705, in run_strip
    subprocess.check_call([strip] + strip_flags + [filename], env=env)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['strip', '-x', '-S', '/Users/josh/dev/joshelson/libchromiumcontent/dist/main/native_mksnapshot/libffmpeg.dylib']' returned non-zero exit status 1
```

The dynlib is properly in the ffmpeg filder, but is NOT in native_mksnapshot. Any easy workaround for this one?

**Comment by MarshallOfSound** [comment]
Hey there,

It's been a long time coming but the `libchromiumcontent` repository is being archived as it is no longer used in the Electron build system (🎉 this is a good thing).

If your issue is still relevant to Electron in it's current build system (please verify first) then you should probably raise a similar issue on `electron/electron`.

Thanks 😄
