### ISSUE TITLE
 Unable to open include file: "windows.h": No such file or directory

### ISSUE THREAD

**Issue by WangMl** [electron/libchromiumcontent#548]
enviroment:
OS: window 10 
visual studio 2015
10.0.14393.0

fatal error C1083: Unable to open include file: "windows.h": No such file or directory?

```
C:/Python27/python.exe ../../build/toolchain/win/tool_wrapper.py cl-wrapper ninja -t msvc -e environment.x64 -- "c:\program files (x86)\microsoft visual studio 14.0\vc\bin\amd64/cl.exe" /nologo /showIncludes  @obj/base/base/wrapped_window_proc.obj.rsp /c ../../base/win/wrapped_window_proc.cc /Foobj/base/base/wrapped_window_proc.obj obj/base "base_cc.pdb"
attention: include file:  E:\workspace\libchromiumcontent\src\base/win/wrapped_window_proc.h
E:\workspace\libchromiumcontent\src\base/win/wrapped_window_proc.h(13): fatal error C1083: Unable to open include file: “windows.h”: No such file or directory
[6/17983] CXX obj/base/base/iat_patch_function.obj
FAILED: obj/base/base/iat_patch_function.obj
C:/Python27/python.exe ../../build/toolchain/win/tool_wrapper.py cl-wrapper ninja -t msvc -e environment.x64 -- "c:\program files (x86)\microsoft visual studio 14.0\vc\bin\amd64/cl.exe" /nologo /showIncludes  @obj/base/base/iat_patch_function.obj.rsp /c ../../base/win/iat_patch_function.cc /Foobj/base/base/iat_patch_function.obj obj/base "base_cc.pdb"
attention: include file:  E:\workspace\libchromiumcontent\src\base/win/iat_patch_function.h
E:\workspace\libchromiumcontent\src\base/win/iat_patch_function.h(8): fatal error C1083: Unable to open include file: “windows.h”: No such file or directory
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File ".\script\build", line 95, in <module>
    sys.exit(main())
  File ".\script\build", line 69, in main
    subprocess.check_call([NINJA, '-C', os.path.relpath(out_dir), target], env=env)
  File "C:\Python27\lib\subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['E:\\workspace\\libchromiumcontent\\vendor\\depot_tools\\ninja.exe', '-C', 'src\\out-x64\\static_library', 'chromiumcontent:chromiumcontent']' returned non-zero exit status 1
```

**Comment by MarshallOfSound** [comment]
Hey there,

It's been a long time coming but the `libchromiumcontent` repository is being archived as it is no longer used in the Electron build system (🎉 this is a good thing).

If your issue is still relevant to Electron in it's current build system (please verify first) then you should probably raise a similar issue on `electron/electron`.

Thanks 😄
