### ISSUE TITLE
Build failed on Windows 10 - 32 bit build 

### ISSUE THREAD

**Issue by anupam** [electron/libchromiumcontent#622]
I am trying to build libchromium content with the custom ffmpeg flags , seeing this error : 

```
17117/18055] CXX obj/third_party/WebKit/Source/modules/media_controls/media_controls/media_controls_jumbo_1.obj
FAILED: obj/third_party/WebKit/Source/modules/media_controls/media_controls/media_controls_jumbo_1.obj
C:/Python27/python.exe ../../build/toolchain/win/tool_wrapper.py cl-wrapper ninja -t msvc -e environment.x86 -- "c:\program files (x86)\microsoft visual studio 14.0\vc\bin\amd64_x86/cl.exe" /nologo /showIncludes  @obj/third_party/WebKit/Source/modules/media_controls/media_controls/media_controls_jumbo_1.obj.rsp /c gen/third_party/WebKit/Source/modules/media_controls/media_controls_jumbo_1.cc /Foobj/third_party/WebKit/Source/modules/media_controls/media_controls/media_controls_jumbo_1.obj obj/third_party/WebKit/Source/modules/media_controls "media_controls_cc.pdb"
gen/third_party/WebKit/Source/modules/media_controls/media_controls_jumbo_1.cc(31): fatal error C1083: Cannot open include file: '../../../../../../../../third_party/WebKit/Source/modules/media_controls/elements/MediaControlToggleClosedCaptionsButtonElement.cpp': No such file or directory
[17126/18055] CXX obj/third_party/WebKit/Source/modules/vr/vr/vr_jumbo_1.obj
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "script\build", line 97, in <module>
    sys.exit(main())
  File "script\build", line 71, in main
    subprocess.check_call([NINJA, '-C', os.path.relpath(out_dir), target], env=env)
  File "C:\Python27\lib\subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\denimuser\\playground\\libchromiumcontent\\vendor\\depot_tools\\ninja.exe', '-C', 'src\\out-ia32\\static_library', 'chromiumcontent:chromiumcontent']' returned non-zero exit status 1
```
Can any one help here ?

Thanks,
Anupam

**Comment by anupam** [comment]
Any help here ?

**Comment by Mikerr1111** [comment]
In the Readme there is a link for Prerequisites and system requirements.

![screenshot_20180824_221006](https://user-images.githubusercontent.com/18353476/44615259-a3f92480-a7ea-11e8-8968-064f686a0e67.png)

The System required is a 64-bit system not a 32-bit system.
![screenshot_20180824_220921](https://user-images.githubusercontent.com/18353476/44615258-9fcd0700-a7ea-11e8-8b24-795aa0536247.png)

**Comment by anupam** [comment]
@Mikerr1111  i am trying to build 32bit binary, my build system is 64 bit and following ever step in the instructions as well.

**Comment by MarshallOfSound** [comment]
Hey there,

It's been a long time coming but the `libchromiumcontent` repository is being archived as it is no longer used in the Electron build system (🎉 this is a good thing).

If your issue is still relevant to Electron in it's current build system (please verify first) then you should probably raise a similar issue on `electron/electron`.

Thanks 😄
